// src/routes/(web)/about/+page.svelte
<div class="flex max-w-lg flex-col gap-2 p-4">
  <header class="text-md font-bold">
    <h1><a href="/">#mem</a></h1>
  </header>

  <main class="flex flex-col gap-2">
    <p>#mem is a memory service that allows you to store text, photos and urls.</p>
    <p>It is designed to be very simple to get data into your account.</p>

    <p>
      Save mems from an iPhone by using this
      <a class="underline" href="https://www.icloud.com/shortcuts/780e5199083447e1ac5257131a995369"
        >Add to Mem Shortcut</a
      >
      or images using this
      <a class="underline" href="https://www.icloud.com/shortcuts/780e5199083447e1ac5257131a995369"
        >Add Photo to Mem Shortcut</a
      >
    </p>
    <p>Save mems from an Android device by using HTTP Shortcuts app and</p>
  </main>
</div>

// src/views/About.vue
<template>
  <div class="flex flex-col gap-2 p-4 max-w-lg">
    <header class="text-md font-bold">
      <h1><a href="/">#mem</a></h1>
    </header>

    <main>
      <p>
        #mem is a memory service that allows you to store text, photos and urls.
      </p>
      <p>It is designed to be very simple to get data into your account.</p>

      <p>
        Save mems from an iPhone by using this
        <a
          href="https://www.icloud.com/shortcuts/780e5199083447e1ac5257131a995369"
          >Add to Mem Shortcut</a
        >
        or images using this
        <a
          href="https://www.icloud.com/shortcuts/780e5199083447e1ac5257131a995369"
          >Add Photo to Mem Shortcut</a
        >
      </p>
      <p>Save mems from an Android device by using HTTP Shortcuts app and</p>
    </main>
  </div>
</template>
